### ISSUE TITLE
1.15.2paper服务器端报错

### ISSUE THREAD

**Issue by dugulingping** [IzzelAliz/Wayback#8]
[02:27:36] [Server thread/WARN]: Legacy plugin Wayback v20.1.2 does not specify an api-version.
[02:27:36] [Server thread/INFO]: [TabooLib] 正在下载资源文件...
[02:27:38] [Server thread/WARN]: java.lang.ClassCastException: jdk.internal.loader.ClassLoaders$AppClassLoader incompatible with java.net.URLClassLoader
[02:27:38] [Server thread/WARN]: 	at com.ilummc.wayback.WaybackLibLoader$Loader.addPath(WaybackLibLoader.java:651)
[02:27:38] [Server thread/WARN]: 	at com.ilummc.wayback.WaybackLibLoader.init(WaybackLibLoader.java:325)
[02:27:38] [Server thread/WARN]: 	at com.ilummc.wayback.WaybackLibLoader.<clinit>(WaybackLibLoader.java:149)
[02:27:38] [Server thread/WARN]: 	at java.base/java.lang.Class.forNameImpl(Native Method)
[02:27:38] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Unknown Source)
[02:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64)
[02:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[02:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
[02:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257)
[02:27:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356)
[02:27:38] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227)
[02:27:38] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:885)
[02:27:38] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[02:27:38] [Server thread/INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.

**Comment by IzzelAliz** [comment]
TabooLib 不支持 Java 9+
